// ==UserScript==
// @name         DCF ChatGPT Microcore
// @namespace    https://chatgpt.com/
// @version      0.9.6
// @description  DCF rollback-first hot/cold update runtime with registry-owned appearance.
// @updateURL    https://raw.githubusercontent.com/ysr7255007-maker/dcf-chatgpt-microcore/main/dcf-chatgpt-microcore.meta.js
// @downloadURL  https://raw.githubusercontent.com/ysr7255007-maker/dcf-chatgpt-microcore/main/dcf-chatgpt-microcore.user.js
// @supportURL   https://github.com/ysr7255007-maker/dcf-chatgpt-microcore
// @match        https://chatgpt.com/*
// @match        https://chat.openai.com/*
// @grant        GM_setClipboard
// @grant        GM_getValue
// @grant        GM_setValue
// @grant        GM_deleteValue
// @grant        GM_listValues
// @grant        GM_addStyle
// @grant        GM_registerMenuCommand
// @grant        GM_notification
// @grant        GM_xmlhttpRequest
// @connect      *
// @run-at       document-idle
// ==/UserScript==
(function(){'use strict';
const V='0.9.6',R='dcf.kernel.registry.v1',S='dcf.kernel.state.v1',B='dcf.kernel.rollback.v1',LT=String.fromCharCode(60),GT=String.fromCharCode(62),NL='\n';
const DEF={appearance:{side:'right',css:'',vars:{w:'340px',bottom:'8px'}},contentTypes:{ammo:{id:'ammo',marker:'DCF_AMMO',title:'语言弹药',body_field:'body',actions:['fire','copy']}},content:{ammo:{}},surfaces:{},modules:[],seenBlocks:{},installedPacks:{}};
let reg=norm(load(R,{})),st=load(S,{tab:'work',pick:'ammo',notice:'',pack:''}),backs=load(B,[]),timer=0;
const host=document.createElement('div'),root=host.attachShadow({mode:'open'});host.id='dcf-chatgpt-microcore-host';root.innerHTML=`<style>.sh{position:fixed;right:12px;bottom:var(--b,8px);width:var(--w,340px);z-index:2147483646;background:#fffffff2;color:#111;border:1px solid #9996;border-radius:14px;box-shadow:0 18px 44px #0002;font:13px system-ui;overflow:hidden}.sh[data-side=left]{left:12px;right:auto}@media(prefers-color-scheme:dark){.sh{background:#171717ee;color:#eee}}button{border:1px solid #9995;border-radius:10px;background:transparent;color:inherit;padding:6px;cursor:pointer}.top{display:flex;gap:6px;padding:5px;border-bottom:1px solid #9993;background:#8881}.main{display:flex;min-height:340px;max-height:calc(100vh - 24px)}.rail{width:42px;overflow:auto;border-right:1px solid #9993;background:#8881}.surf{writing-mode:vertical-rl;margin:5px;min-height:50px}.body{flex:1;overflow:auto;padding:9px}.card{position:relative;border:1px solid #9994;border-radius:12px;background:#8881;padding:9px;margin-bottom:9px}.name{font-weight:700}.mini,.desc{font-size:12px;opacity:.7}.actions{display:flex;flex-wrap:wrap;gap:7px;margin-top:9px}.del{position:absolute;top:5px;right:5px;border-radius:999px}.on{background:#2563eb22;border-color:#2563eb66}.warn{background:#d9770622}textarea{width:100%;min-height:88px}</style><style id='ap'></style><aside class='sh'></aside>`;document.documentElement.appendChild(host);const sh=root.querySelector('.sh');sh.onclick=click;sh.oninput=e=>{if(e.target.dataset.role==='pack'){st.pack=e.target.value;save(S,st)}};menu();render();scanSoon(250);new MutationObserver(()=>scanSoon(800)).observe(document.body,{childList:true,subtree:true,characterData:true});
function render(){let a=reg.appearance||{};sh.dataset.side=a.side||'right';sh.style.setProperty('--w',a.vars?.w||'340px');sh.style.setProperty('--b',a.vars?.bottom||'8px');root.getElementById('ap').textContent=String(a.css||'').slice(0,10000);let ss=surfs();sh.innerHTML=`<div class='top'><b>DCF ${V}</b><button data-act='tab' data-tab='work' class='${st.tab==='work'?'on':''}'>工作</button><button data-act='tab' data-tab='maint' class='${st.tab==='maint'?'on':''}'>维护</button>${st.notice?`<button data-act='clear'>✓</button>`:''}<span style='flex:1'></span><button data-act='side'>侧</button></div><div class='main'><div class='rail'>${ss.map(x=>`<button class='surf' data-act='pick' data-id='${h(x.id)}'>${h(x.title)}</button>`).join('')}</div><div class='body'>${body()}</div></div>`}
function surfs(){return st.tab==='maint'?[{id:'status',title:'状态'},{id:'recovery',title:'恢复'},{id:'install',title:'安装'},{id:'ammo',title:'弹药'}]:[{id:'ammo',title:'弹药'}].concat(Object.values(reg.surfaces||{}))}
function body(){let id=st.pick||'ammo';if(id==='status')return card('状态',`<div class='mini'>modules ${reg.modules.length} · backups ${backs.length}</div><div class='actions'><button data-act='diag'>复制诊断</button><button data-act='scan'>扫描</button><button data-act='snap'>建恢复点</button></div>`);if(id==='recovery')return card('恢复',`<div class='mini'>更新前快照，失败可回滚。风险靠恢复点兜住，不靠版本/热更新分类兜住。</div><div class='actions'><button data-act='rollback-last' class='on'>回滚上一个</button><button data-act='export'>导出 registry</button><button data-act='safe'>最小外观</button></div>${backs.slice(-8).reverse().map(b=>card(b.id,`<div class='mini'>${h(b.at)} · ${h(b.reason)}</div><button data-act='rollback' data-id='${h(b.id)}'>回滚</button>`)).join('')}`);if(id==='install')return card('安装',`<textarea data-role='pack'>${h(st.pack)}</textarea><div class='actions'><button data-act='apply' class='on'>应用</button><button data-act='sample'>样例</button></div>`);if(id==='ammo')return library('ammo');let s=reg.surfaces[id];return s?card(s.title||id,node(s.body||s.tree||'')):'<div class=card>没有内容</div>'}
function library(t){let typ=reg.contentTypes[t]||{},acts=typ.actions||['fire','copy'],xs=Object.values(reg.content[t]||{});return xs.length?xs.map(x=>`<div class='card'>${acts.includes('remove')?`<button class='del warn' data-act='remove' data-type='${t}' data-id='${h(x.id)}'>×</button>`:''}<div class='name'>${h(x.title||x.id)}</div><div class='desc'>${h(x.purpose||x.kind||'')}</div><div class='actions'>${acts.filter(a=>a!=='remove').map(a=>`<button data-act='${a}' data-type='${t}' data-id='${h(x.id)}' class='${a==='fire'?'on':''}'>${a==='fire'?'发射':a==='copy'?'复制':a==='update'?'更新':h(a)}</button>`).join('')}</div></div>`).join(''):'<div class=card>没有内容资产</div>'}
function card(t,b){return`<div class='card'><div class='name'>${h(t)}</div>${b}</div>`}function node(n){if(!n)return'';if(typeof n==='string')return h(n);if(Array.isArray(n))return n.map(node).join('');if(n.type==='contentLibrary'||n.type==='content_library')return library(n.content_type||'ammo');return card(n.title||'',node(n.children||n.body||n.text||''))}
function click(e){let n=e.target.closest('[data-act]');if(!n)return;let a=n.dataset.act;if(a==='tab'){st.tab=n.dataset.tab;st.pick=surfs()[0]?.id;save(S,st);render()}else if(a==='pick'){st.pick=n.dataset.id;save(S,st);render()}else if(a==='clear'){st.notice='';save(S,st);render()}else if(a==='side'){reg.appearance.side=reg.appearance.side==='left'?'right':'left';saveReg();render()}else if(a==='diag'){clip(JSON.stringify(diag(),null,2));notice('诊断已复制')}else if(a==='scan')scan(true);else if(a==='snap'){let id=snapshot('manual');saveB();notice('恢复点 '+id)}else if(a==='rollback-last')rollback();else if(a==='rollback')rollback(n.dataset.id);else if(a==='export'){clip(JSON.stringify(reg,null,2));notice('registry 已复制')}else if(a==='safe'){snapshot('safe');reg.appearance=clone(DEF.appearance);saveReg();saveB();render()}else if(a==='apply')applyBox();else if(a==='sample'){clip(JSON.stringify(sample(),null,2));notice('样例已复制')}else if(a==='fire')fire(n.dataset.type,n.dataset.id);else if(a==='copy')copyItem(n.dataset.type,n.dataset.id);else if(a==='update')updateItem(n.dataset.type,n.dataset.id);else if(a==='remove')removeItem(n.dataset.type,n.dataset.id)}
function scanSoon(ms){clearTimeout(timer);timer=setTimeout(()=>scan(false),ms)}function scan(manual){let text=document.body.innerText||'';find(text,'DCF_MODULE_PACK').forEach(raw=>{let hh=hash(raw);if(reg.seenBlocks[hh]&&!manual)return;try{applyPack(JSON.parse(raw),hh)}catch(e){feedback({event:'module_install',status:'failed',error:e.message})}});Object.values(reg.contentTypes).forEach(t=>t.marker&&find(text,t.marker).forEach(raw=>{let hh='content:'+t.id+':'+hash(raw);if(reg.seenBlocks[hh]&&!manual)return;try{ingest(t.id,JSON.parse(raw));reg.seenBlocks[hh]={status:'ingested'}}catch{reg.seenBlocks[hh]={status:'rejected'}}}));saveReg();render()}function find(text,tag){let o=LT+LT+LT+tag,c=tag+GT+GT+GT,r=[],p=0;for(;;){let s=text.indexOf(o,p);if(s<0)break;let e=text.indexOf(c,s+o.length);if(e<0)break;r.push(text.slice(s+o.length,e).trim());p=e+c.length}return r}
function applyBox(){try{applyPack(JSON.parse(st.pack||'{}'),hash(st.pack))}catch(e){notice('解析失败：'+e.message)}}function applyPack(p,hh){if(!p||p.schema!=='dcf.module_pack.v1')throw Error('bad_schema');let sid=snapshot('before_apply',{hash:hh});let x=p.contributes||{};if(x.appearance||p.appearance)reg.appearance=merge(reg.appearance,x.appearance||p.appearance);if(x.styles||p.styles)reg.appearance.vars=merge(reg.appearance.vars||{},styleVars(x.styles||p.styles));if(x.ui_policy||p.ui_policy)reg.appearance=merge(reg.appearance,legacy(x.ui_policy||p.ui_policy));(x.content_types||p.content_types||[]).forEach(t=>{reg.contentTypes[t.id]=merge(reg.contentTypes[t.id]||{},t);reg.content[t.id]=reg.content[t.id]||{}});Object.entries(x.content||p.content||{}).forEach(([t,arr])=>(arr||[]).forEach(it=>ingest(t,it)));(x.surfaces||p.surfaces||[]).forEach(s=>{if(s&&s.id)reg.surfaces[s.id]=s});(p.modules||[]).forEach(m=>{if(m&&m.id)reg.modules.push(m)});reg.installedPacks[(p.pack_id||'pack')+'@'+(p.revision||hh)]={snapshot_id:sid};reg.seenBlocks[hh]={status:'installed',snapshot_id:sid};saveReg();saveB();notice('热更新完成，可回滚');feedback({event:'module_install',status:'ok',pack_id:p.pack_id,revision:p.revision,installed_modules:(p.modules||[]).map(m=>m.id),warnings:[],contributions:{count:1},source_hash:hh,snapshot_id:sid})}
function ingest(t,it){if(it&&it.id){reg.content[t]=reg.content[t]||{};reg.content[t][it.id]={...it,id:String(it.id),title:String(it.title||it.id)}}}function field(t){return(reg.contentTypes[t]||{}).body_field||'body'}function fire(t,id){let it=reg.content[t]?.[id];if(it)insert(String(it[field(t)]||it.body||it.text||''),'replace')}function copyItem(t,id){let it=reg.content[t]?.[id];if(it){clip(String(it[field(t)]||it.body||it.text||''));notice('已复制')}}function updateItem(t,id){let it=reg.content[t]?.[id];if(!it)return;let q='请基于当前对话的新洞见更新下面原内容。输出完整可重新摄取内容块；不需要更新则说明理由。\n\n原内容 JSON：\n'+JSON.stringify(it,null,2);readComposer().trim()?(clip(q),notice('更新请求已复制')):(insert(q,'replace'),send())}function removeItem(t,id){if(confirm('删除内容资产？')){snapshot('before_remove');delete reg.content[t][id];saveReg();saveB();render()}}
function snapshot(reason,meta={}){let id='rb_'+Date.now().toString(36);backs.push({id,at:new Date().toISOString(),reason,meta,registry_json:JSON.stringify(reg)});backs=backs.slice(-18);return id}function rollback(id){id=id||backs.at(-1)?.id;if(id&&confirm('回滚到 '+id+'？')){let b=backs.find(x=>x.id===id);if(b){reg=norm(JSON.parse(b.registry_json));saveReg();saveB();render();notice('已回滚')}}}
function norm(v){v=merge(clone(DEF),v||{});v.appearance=merge(clone(DEF.appearance),v.appearance||{});Object.keys(v.contentTypes).forEach(k=>v.content[k]=v.content[k]||{});return v}function legacy(p){let o={};if(p.chrome_mode)o.chrome=p.chrome_mode;if(p.shell_bottom_css)o.vars={bottom:p.shell_bottom_css};if(p.panel_width_css)o.vars=merge(o.vars||{},{w:p.panel_width_css});return o}function styleVars(s){let v={};if(s.shell_bottom_css)v.bottom=s.shell_bottom_css;if(s.panel_width_css)v.w=s.panel_width_css;return v}function sample(){return{schema:'dcf.module_pack.v1',pack_id:'dcf.sample.rollback_first',revision:new Date().toISOString(),contributes:{appearance:{side:'right',vars:{bottom:'10px',w:'340px'}}},modules:[]}}
function load(k,d){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}}function save(k,v){localStorage.setItem(k,JSON.stringify(v))}function saveReg(){save(R,reg)}function saveB(){save(B,backs)}function menu(){if(typeof GM_registerMenuCommand==='function'){GM_registerMenuCommand('DCF rollback last',()=>rollback());GM_registerMenuCommand('DCF diagnostics',()=>clip(JSON.stringify(diag(),null,2)))}}function diag(){return{schema:'dcf.diagnostics.v1',kernel_version:V,backups:backs.length,modules:reg.modules.length,content_types:Object.keys(reg.contentTypes).length,appearance_owned_by_registry:true}}function feedback(d){let t=['<<<DCF_FEEDBACK',JSON.stringify({schema:'dcf.feedback.v1',kernel_version:V,at:new Date().toISOString(),...d},null,2),'DCF_FEEDBACK>>>'].join(NL);readComposer().trim()?(clip(t),notice('反馈已复制')):(insert(t,'replace'),send())}
function composer(){return[...document.querySelectorAll('#prompt-textarea,textarea,[contenteditable=true],div.ProseMirror')].find(n=>n instanceof HTMLElement&&n.getBoundingClientRect().height>0&&!host.contains(n))}function readComposer(){let n=composer();return n?(n.value||n.innerText||n.textContent||''):''}function insert(t,mode){let n=composer(),v=String(t||'');if(!n){clip(v);return}n.focus();if(n.value!=null){n.value=mode==='replace'?v:n.value+v;n.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText',data:v}))}else{if(mode==='replace')n.textContent='';document.execCommand('insertText',false,v);n.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText',data:v}))}}async function send(){for(let i=0;i<30;i++){for(let b of document.querySelectorAll('button[type=submit],button[data-testid=send-button],button[data-testid=composer-send-button]'))if(b instanceof HTMLElement&&b.getBoundingClientRect().height>0&&!b.disabled){b.click();return}await new Promise(r=>setTimeout(r,180))}}function clip(v){typeof GM_setClipboard==='function'?GM_setClipboard(String(v||'')):navigator.clipboard?.writeText(String(v||''))}function notice(t){st.notice=String(t||'');save(S,st);render()}function h(v){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;')}function merge(a,b){a=clone(a);Object.entries(b||{}).forEach(([k,v])=>a[k]=v&&typeof v==='object'&&!Array.isArray(v)?merge(a[k]||{},v):clone(v));return a}function clone(v){return JSON.parse(JSON.stringify(v||{}))}function hash(s){let v=5381;s=String(s||'');for(let i=0;i<s.length;i++)v=((v<<5)+v)^s.charCodeAt(i);return'h'+(v>>>0).toString(16)}
})();