'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const childProcess = require('child_process');
const root = path.resolve(__dirname, '..');
childProcess.execFileSync(process.execPath, ['scripts/build-chrome-extension.js'], { cwd: root, stdio: 'inherit' });
const extension = path.join(root, 'dist/dcf-chrome-extension');
const manifest = JSON.parse(fs.readFileSync(path.join(extension, 'manifest.json'), 'utf8'));
const config = JSON.parse(fs.readFileSync(path.join(extension, 'config.json'), 'utf8'));
const index = JSON.parse(fs.readFileSync(path.join(root, 'releases/chrome/official-index.json'), 'utf8'));
assert.strictEqual(manifest.version_name, '1.0.0-rc.2');
assert.strictEqual(manifest.version, '1.0.0.2');
assert.strictEqual(config.schema, 'dcf.chrome.config.v1');
assert(config.plugin_index_url.includes('/rebuild/chrome-native-host-v2/'));
assert.strictEqual(index.schema, 'dcf.plugin_index.v1');
assert.strictEqual(index.units.length, 8);
assert.strictEqual(new Set(index.units.map((unit) => unit.world_id)).size, index.units.length);
assert.strictEqual(new Set(index.units.map((unit) => unit.id)).size, index.units.length);
for (const unit of index.units) {
  assert(/^[a-f0-9]{64}$/.test(unit.hash));
  assert(unit.code_url.includes(`/chrome-extension/code-units/`));
}
assert(!fs.existsSync(path.join(extension, 'official/code-units.json')));
const extensionJs = fs.readdirSync(path.join(extension, 'src')).map((name) => fs.readFileSync(path.join(extension, 'src', name), 'utf8')).join('\n');
assert(!extensionJs.includes('〔DCF·语言弹药〕'));
assert(!extensionJs.includes('长对话减负'));
const css = fs.readFileSync(path.join(extension, 'pages/common.css'), 'utf8');
assert(css.includes('--text:'));
assert(/@media\s*\(prefers-color-scheme:dark\)/.test(css));
assert(/--text:\s*#f3f4f6/.test(css));
const migration = fs.readFileSync(path.join(extension, 'static/migration-bridge.js'), 'utf8');
assert(migration.includes('dcf-next-shell-host'));
assert(!migration.includes('dcf-chatgpt-microcore-host'));
console.log(JSON.stringify({ ok: true, pure_base: true, independent_plugins: 8, dark_mode: true, next_migration_only: true }, null, 2));
