'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const childProcess = require('child_process');
const root = path.resolve(__dirname, '..');
const zip = path.join(root, 'dist', 'dcf-chrome-extension-1.0.0-rc.1.zip');
const summary = path.join(root, 'dist', 'verification-summary.json');
const digest = (filename) => crypto.createHash('sha256').update(fs.readFileSync(filename)).digest('hex');
childProcess.execFileSync(process.execPath, [path.join(root, 'scripts', 'build-chrome-extension.js')], { cwd: root, stdio: 'ignore' });
const first = { zip: digest(zip), summary: digest(summary) };
childProcess.execFileSync(process.execPath, [path.join(root, 'scripts', 'build-chrome-extension.js')], { cwd: root, stdio: 'ignore' });
const second = { zip: digest(zip), summary: digest(summary) };
assert.deepStrictEqual(second, first);
console.log(JSON.stringify({ ok: true, deterministic_zip: first.zip, deterministic_summary: first.summary }, null, 2));
