(function(){'use strict';
const UNIT_ID='dcf.firstparty.attribution',UNIT_VERSION='1.0.0-rc.2',PANEL_ID='attribution',HOST_ID='dcf-panel-attribution',GLOBAL='__DCF_FIRSTPARTY_ATTRIBUTION__';const send=(m)=>chrome.runtime.sendMessage(m).then(r=>{if(!r||r.ok===false)throw new Error(r&&r.error||'DCF host rejected request');return r;});const prev=globalThis[GLOBAL];if(prev?.destroy)prev.destroy();
let panel,state='idle',session=null,report=null,observers=[],timeout=null,replyObserver=null,pending=new Map();let clickListener,keyListener;
function clearObservers(){for(const o of observers)try{o.disconnect();}catch(_){}observers=[];clearTimeout(timeout);}function addObserver(type,handler){try{const o=new PerformanceObserver(l=>handler(l.getEntries()));o.observe({type,buffered:false});observers.push(o);}catch(_){}}
function startSampling(at){if(state!=='armed')return;state='running';session={started_at_wall:new Date().toISOString(),send_at:at,first_activity_at:null,completion_at:null,entries:{loaf:[],longtask:[],event:[],layout_shift:[]}};addObserver('long-animation-frame',e=>session.entries.loaf.push(...e.map(x=>({startTime:x.startTime,duration:x.duration,blockingDuration:x.blockingDuration||null,renderStart:x.renderStart||null,styleAndLayoutStart:x.styleAndLayoutStart||null}))));addObserver('longtask',e=>session.entries.longtask.push(...e.map(x=>({startTime:x.startTime,duration:x.duration}))));addObserver('event',e=>session.entries.event.push(...e.filter(x=>x.duration>=16).slice(0,80).map(x=>({name:x.name,startTime:x.startTime,duration:x.duration,processingStart:x.processingStart,processingEnd:x.processingEnd}))));addObserver('layout-shift',e=>session.entries.layout_shift.push(...e.filter(x=>!x.hadRecentInput).map(x=>({startTime:x.startTime,value:x.value}))));timeout=setTimeout(()=>finish('timeout'),10*60*1000);render();}
function finish(reason='completed'){if(state!=='running'||!session)return;clearObservers();session.completion_at=session.completion_at||performance.now();const first=session.first_activity_at,end=session.completion_at;report={schema:'dcf.conversation-turn-attribution.v1',generated_at:new Date().toISOString(),reason,route_kind:location.pathname,send_to_first_reply_activity_ms:first?Math.round(first-session.send_at):null,first_reply_activity_to_completion_ms:first?Math.round(end-first):null,total_ms:Math.round(end-session.send_at),completion_quiet_window_ms:1100,browser_observation:{loaf_count:session.entries.loaf.length,loaf_total_duration_ms:Math.round(session.entries.loaf.reduce((s,x)=>s+x.duration,0)),longtask_count:session.entries.longtask.length,longtask_total_duration_ms:Math.round(session.entries.longtask.reduce((s,x)=>s+x.duration,0)),slow_event_count:session.entries.event.length,layout_shift_value:Math.round(session.entries.layout_shift.reduce((s,x)=>s+x.value,0)*10000)/10000,loaf:session.entries.loaf.slice(0,80),longtasks:session.entries.longtask.slice(0,80),events:session.entries.event.slice(0,80),layout_shifts:session.entries.layout_shift.slice(0,80)},limits:['等待阶段同时包含服务端、网络、页面调度和浏览器工作，不能仅凭耗时归因给前端。','浏览器性能 API 只能描述可观察工作。','报告不包含提示词、回复正文、DOM 文本、事件目标、完整 URL、调用栈或认证信息。']};state='completed';session=null;render();}
function arm(){clearObservers();state='armed';report=null;session=null;render();}function cancel(){clearObservers();state='idle';report=null;session=null;render();}
function composerSelector(){return'#prompt-textarea,[data-testid="composer-text-input"],form textarea,main [contenteditable="true"]';}function sendSelector(){return'[data-testid="send-button"],button[aria-label*="Send"],button[aria-label*="发送"]';}
function scheduleCompletion(node){if(!node||pending.has(node))return;const rec={last:'',stable:performance.now()};pending.set(node,rec);if(state==='running'&&session&&!session.first_activity_at){session.first_activity_at=performance.now();render();}const check=()=>{if(!node.isConnected){pending.delete(node);return;}const t=String(node.innerText||node.textContent||'').trim(),now=performance.now();if(t!==rec.last){rec.last=t;rec.stable=now;}if(t&&!document.querySelector('[data-testid="stop-button"],button[aria-label*="Stop"],button[aria-label*="停止"]')&&now-rec.stable>=1100){pending.delete(node);if(state==='running'&&session){session.completion_at=now;finish('completed');}return;}rec.timer=setTimeout(check,350);};rec.timer=setTimeout(check,350);}
function attachReplyObserver(){const root=document.querySelector('main')||document.querySelector('[role="main"]');if(!root){setTimeout(attachReplyObserver,900);return;}replyObserver?.disconnect();replyObserver=new MutationObserver(records=>{for(const rec of records)for(const n of rec.addedNodes){if(!(n instanceof Element))continue;if(n.matches?.('[data-message-author-role="assistant"]'))scheduleCompletion(n);for(const c of n.querySelectorAll?.('[data-message-author-role="assistant"]')||[])scheduleCompletion(c);}});replyObserver.observe(root,{childList:true,subtree:true});}
function style(){return`:host{display:block;font:13px/1.5 system-ui;color:inherit}.card{border:1px solid #ddd;border-radius:10px;padding:10px;background:#fff}.row{display:flex;gap:8px;align-items:center;flex-wrap:wrap}button{font:inherit;color:inherit;border:1px solid #bbb;background:#fff;border-radius:8px;padding:6px 9px}.primary{background:#202124;color:#fff;border-color:#202124}pre{white-space:pre-wrap;font:11px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace;background:#f4f4f4;padding:8px;border-radius:8px}@media(prefers-color-scheme:dark){.card{background:#222;border-color:#444}button{background:#292929;color:#f3f3f3;border-color:#555}.primary{background:#f3f3f3;color:#181818}pre{background:#171717}}`;}
function render(){if(!panel)return;const r=panel.shadowRoot;r.querySelector('.content').innerHTML=`<section class="card"><b>${({idle:'未启动',armed:'等待下一次发送',running:'记录中',completed:'已完成，可复制'})[state]}</b><div class="row"><button class="primary" data-action="arm" ${state==='running'?'disabled':''}>记录下一轮问答</button><button data-action="finish" ${state!=='running'?'disabled':''}>手动结束</button><button data-action="copy" ${!report?'disabled':''}>复制本轮归因报告</button><button data-action="clear">清除</button></div>${report?`<pre>${JSON.stringify({total_ms:report.total_ms,send_to_first_reply_activity_ms:report.send_to_first_reply_activity_ms,first_reply_activity_to_completion_ms:report.first_reply_activity_to_completion_ms,browser_observation:report.browser_observation},null,2)}</pre>`:''}</section>`;r.querySelector('[data-action="arm"]').onclick=arm;r.querySelector('[data-action="finish"]').onclick=()=>finish('manual');r.querySelector('[data-action="copy"]').onclick=()=>navigator.clipboard.writeText(JSON.stringify(report,null,2));r.querySelector('[data-action="clear"]').onclick=cancel;}
function createPanel(){panel=document.createElement('section');panel.id=HOST_ID;panel.dataset.dcfPanelRoot='true';panel.dataset.dcfPanelId=PANEL_ID;panel.dataset.dcfPanelTitle='归因';panel.style.display='none';const r=panel.attachShadow({mode:'open'});r.innerHTML=`<style>${style()}</style><div class="content"></div>`;document.documentElement.append(panel);document.dispatchEvent(new CustomEvent('dcf:panel-ready',{detail:PANEL_ID}));}
function destroy(){clearObservers();replyObserver?.disconnect();for(const rec of pending.values())clearTimeout(rec.timer);pending.clear();document.removeEventListener('click',clickListener,true);document.removeEventListener('keydown',keyListener,true);panel?.remove();}globalThis[GLOBAL]={version:UNIT_VERSION,destroy};
try{document.getElementById(HOST_ID)?.remove();createPanel();render();clickListener=e=>{if(e.target?.closest?.(sendSelector()))startSampling(performance.now());};keyListener=e=>{if(e.key==='Enter'&&!e.shiftKey&&e.target?.closest?.(composerSelector()))startSampling(performance.now());};document.addEventListener('click',clickListener,true);document.addEventListener('keydown',keyListener,true);attachReplyObserver();send({type:'unit.started',unit_id:UNIT_ID,version:UNIT_VERSION}).catch(e=>send({type:'unit.failed',unit_id:UNIT_ID,version:UNIT_VERSION,error:String(e?.message||e)}));}catch(e){destroy();send({type:'unit.failed',unit_id:UNIT_ID,version:UNIT_VERSION,error:String(e?.message||e)}).catch(()=>{});}
})();
