from pathlib import Path

p = Path('chrome-extension/code-units/local-agent-dialogue/main.js')
s = p.read_text()
if "local-agent-dialogue.7" in s:
    raise SystemExit(0)

def one(old, new):
    global s
    if s.count(old) != 1:
        raise RuntimeError(f'expected one match: {old[:80]!r}; got {s.count(old)}')
    s = s.replace(old, new, 1)

one("const UNIT_VERSION = '1.0.0-rc.2-local-agent-dialogue.6';", "const UNIT_VERSION = '1.0.0-rc.2-local-agent-dialogue.7';")
one("  const LOCAL_AGENT_PANEL_ID = 'dcf-panel-local-agent';\n", "  const LOCAL_AGENT_PANEL_ID = 'dcf-panel-local-agent';\n  const SHELL_HOST_ID = 'dcf-chrome-shell-host';\n")
one("  let panelObserver = null;\n", "  let panelObserver = null;\n  let shellObserver = null;\n")
one("  let currentPanelShadow = null;\n", "  let currentPanelShadow = null;\n  let currentShellShadow = null;\n")
one("  let elapsedTimer = null;\n", "  let elapsedTimer = null;\n  let shellReadyListener = null;\n  let panelReadyListener = null;\n")
one("  function localPanelHost() { return document.getElementById(LOCAL_AGENT_PANEL_ID); }\n  function localPanelShadow() { return localPanelHost()?.shadowRoot || null; }\n", "  function shellShadow() { return document.getElementById(SHELL_HOST_ID)?.shadowRoot || null; }\n  function localPanelHost() {\n    return document.getElementById(LOCAL_AGENT_PANEL_ID)\n      || shellShadow()?.querySelector(`#${LOCAL_AGENT_PANEL_ID}`)\n      || null;\n  }\n  function localPanelShadow() { return localPanelHost()?.shadowRoot || null; }\n")
one("  const sessionId = (session) => String(session?.id || session?.sessionID || session?.session_id || '');\n  const statusType = (value) => String(typeof value === 'string' ? value : value?.type || value?.status || value?.state || 'unknown').toLowerCase();\n  const messageRole = (record) => String(record?.info?.role || record?.info?.type || '').toLowerCase();\n", "  const sessionId = (session) => String(session?.id || session?.sessionID || session?.session_id || '');\n  const statusType = (value, fallback = 'unknown') => String(typeof value === 'string' ? value : value?.type || value?.status || value?.state || fallback).toLowerCase();\n  function statusCollection(value) {\n    if (!value || typeof value !== 'object') return {};\n    if (value.sessions && typeof value.sessions === 'object' && !Array.isArray(value.sessions)) return value.sessions;\n    if (value.data?.sessions && typeof value.data.sessions === 'object' && !Array.isArray(value.data.sessions)) return value.data.sessions;\n    if (value.data && typeof value.data === 'object' && !Array.isArray(value.data)) return value.data;\n    return value;\n  }\n  function sessionStatusFrom(value, id) {\n    const collection = statusCollection(value);\n    return collection?.[id]\n      || list(collection).find((item) => String(item?.sessionID || item?.session_id || item?.sessionId || item?.id || '') === id)\n      || null;\n  }\n  const messageRole = (record) => String(record?.info?.role || record?.info?.type || '').toLowerCase();\n")
one("    const statusesData = statuses.ok ? statuses.data : null;\n    const sessionStatus = statusesData?.[job.session_id] || list(statusesData).find((item) => String(item?.sessionID || item?.session_id || item?.id || '') === job.session_id) || null;\n", "    const sessionStatus = statuses.ok ? sessionStatusFrom(statuses.data, job.session_id) : null;\n    const normalizedStatus = sessionStatus\n      ? statusType(sessionStatus)\n      : statuses.ok\n        ? (job.response_state === 'fulfilled' ? 'idle' : 'message-pending')\n        : 'status-unavailable';\n")
one("      status: sessionStatus, status_type: statusType(sessionStatus), messages: messageList,", "      status: sessionStatus, status_type: normalizedStatus, messages: messageList,")
one("  function updateProgress(snap, job) {\n    const preview = latestAssistant(snap.messages);\n    const effectiveStatus = job?.response_state === 'pending' && snap.status_type === 'unknown' ? 'message-pending' : snap.status_type;\n    state.progress = {\n      status_type: effectiveStatus, messages: snap.messages.length, todo: snap.todo.length, diff: snap.diff.length,\n", "  function updateProgress(snap) {\n    const preview = latestAssistant(snap.messages);\n    state.progress = {\n      status_type: snap.status_type, messages: snap.messages.length, todo: snap.todo.length, diff: snap.diff.length,\n")
one("        status_type: job.response_state === 'pending' && snap.status_type === 'unknown' ? 'message-pending' : snap.status_type,", "        status_type: snap.status_type,")
s = s.replace('updateProgress(snap, job);', 'updateProgress(snap);').replace('updateProgress(finalSnap, job);', 'updateProgress(finalSnap);')
old = """  function cardHtml() {
    const active = Boolean(activeJob) || ['checking', 'creating', 'submitting'].includes(state.stage);
    const progress = state.progress;
    return `<section class="card"><div class="title-row"><b>对话闭环</b><span class="status ${active ? 'busy' : state.settings.enabled ? 'ready' : ''}">${active ? '执行中' : state.settings.enabled ? '已开启' : '已关闭'}</span></div><div class="muted">只消费插件启动后新增的助手回复。页面中已有历史消息只建立基线，不会被重新执行。</div><div class="row"><label class="row"><input type="checkbox" data-field="enabled" ${state.settings.enabled ? 'checked' : ''}>允许对话自动委派</label><label class="row"><input type="checkbox" data-field="auto-send" ${state.settings.auto_send_results ? 'checked' : ''}>结果自动发送回对话</label></div><div class="stage"><b>${html(state.status)}</b>${elapsedText() ? ` · ${html(elapsedText())}` : ''}<br>阶段：${html(state.stage)}${state.last_request_id ? `<br>请求：${html(state.last_request_id)}` : ''}${state.last_session_id ? `<br>会话：${html(state.last_session_id)}` : ''}</div><div class="progress"><div class="metric"><span class="muted">状态</span><b>${html(progress.status_type || '—')}</b></div><div class="metric"><span class="muted">消息</span><b>${progress.messages}</b></div><div class="metric"><span class="muted">Todo</span><b>${progress.todo}</b></div><div class="metric"><span class="muted">Diff</span><b>${progress.diff}</b></div><div class="metric"><span class="muted">权限</span><b>${progress.permissions}</b></div><div class="metric"><span class="muted">提问</span><b>${progress.questions}</b></div></div>${progress.preview ? `<div><div class="muted">最近本机输出 · ${html(progress.last_poll_at)}</div><div class="preview">${html(progress.preview)}</div></div>` : ''}<div class="buttons"><button data-action="latest">检查最新助手回复</button><button data-action="focus">查看执行会话</button><button data-action="return">回传待发送结果</button><button data-action="clear">清除已处理记录</button></div><div class="last-action muted">上次操作：${html(state.last_action)}${state.last_action_at ? ` · ${html(state.last_action_at)}` : ''}</div>${state.error ? `<div class="notice error">${html(state.error)}</div>` : ''}</section>`;
  }
"""
new = """  function cardHtml() {
    const active = Boolean(activeJob) || queueBusy || ['received', 'checking', 'creating', 'submitting', 'running', 'needs_user'].includes(state.stage);
    const progress = state.progress;
    const activeRequestId = activeJob?.request?.id || (active ? state.last_request_id : '');
    const activeSessionId = activeJob?.session_id || (active ? state.last_session_id : '');
    const recent = !active && (state.last_request_id || state.last_session_id)
      ? `<div class="muted">最近交接${state.last_request_id ? ` · 请求 ${html(state.last_request_id)}` : ''}${state.last_session_id ? ` · 会话 ${html(state.last_session_id)}` : ''}</div>`
      : '';
    return `<section class="card"><div class="title-row"><b>对话闭环</b><span class="status ${active ? 'busy' : state.settings.enabled ? 'ready' : ''}">${active ? '执行中' : state.settings.enabled ? '已开启' : '已关闭'}</span></div><div class="muted">只消费插件启动后新增的助手回复。页面中已有历史消息只建立基线，不会被重新执行。</div><div class="row"><label class="row"><input type="checkbox" data-field="enabled" ${state.settings.enabled ? 'checked' : ''}>允许对话自动委派</label><label class="row"><input type="checkbox" data-field="auto-send" ${state.settings.auto_send_results ? 'checked' : ''}>结果自动发送回对话</label></div><div class="stage"><b>${html(state.status)}</b>${elapsedText() ? ` · ${html(elapsedText())}` : ''}<br>阶段：${html(state.stage)}${activeRequestId ? `<br>当前请求：${html(activeRequestId)}` : ''}${activeSessionId ? `<br>当前会话：${html(activeSessionId)}` : ''}</div>${recent}<div class="progress"><div class="metric"><span class="muted">状态</span><b>${html(progress.status_type || '—')}</b></div><div class="metric"><span class="muted">消息</span><b>${progress.messages}</b></div><div class="metric"><span class="muted">Todo</span><b>${progress.todo}</b></div><div class="metric"><span class="muted">Diff</span><b>${progress.diff}</b></div><div class="metric"><span class="muted">权限</span><b>${progress.permissions}</b></div><div class="metric"><span class="muted">提问</span><b>${progress.questions}</b></div></div>${progress.preview ? `<div><div class="muted">最近本机输出 · ${html(progress.last_poll_at)}</div><div class="preview">${html(progress.preview)}</div></div>` : ''}<div class="buttons"><button data-action="latest">检查最新助手回复</button><button data-action="focus">查看最近执行会话</button><button data-action="return">回传待发送结果</button><button data-action="clear">清除已处理记录</button></div><div class="last-action muted">上次操作：${html(state.last_action)}${state.last_action_at ? ` · ${html(state.last_action_at)}` : ''}</div>${state.error ? `<div class="notice error">${html(state.error)}</div>` : ''}</section>`;
  }
"""
one(old, new)
one("      state.processed_ids = []; state.last_request_id = ''; state.stage = 'idle';\n      state.status = '已清除工件去重记录；历史消息仍不会自动执行'; state.error = '';\n      markAction('已清除工件去重记录'); await persist(); render();", "      state.processed_ids = []; state.last_request_id = ''; state.last_session_id = ''; state.stage = 'idle';\n      state.progress = { status_type: '', messages: 0, todo: 0, diff: 0, permissions: 0, questions: 0, preview: '', last_poll_at: '' };\n      state.status = '已清除工件去重记录与最近交接；历史消息仍不会自动执行'; state.error = '';\n      markAction('已清除工件去重记录与最近交接'); await persist(); render();")
one("  function attachHotRefreshWatchers() {\n", "  function attachShellObserver() {\n    const shadow = shellShadow();\n    if (shadow === currentShellShadow) return Boolean(shadow);\n    shellObserver?.disconnect();\n    currentShellShadow = shadow;\n    if (!shadow) return false;\n    shellObserver = new MutationObserver(schedulePanelMount);\n    shellObserver.observe(shadow, { childList: true, subtree: true });\n    schedulePanelMount();\n    return true;\n  }\n\n  function attachHotRefreshWatchers() {\n")
one("          if (node.id === LOCAL_AGENT_PANEL_ID || node.querySelector?.(`#${LOCAL_AGENT_PANEL_ID}`)) panelChanged = true;\n        }\n      }\n      if (panelChanged) schedulePanelMount();\n      if (rootChanged) attachConversationRoot();\n    });\n    documentObserver.observe(document.documentElement, { childList: true, subtree: true });\n    schedulePanelMount();\n", "          if (node.id === LOCAL_AGENT_PANEL_ID || node.querySelector?.(`#${LOCAL_AGENT_PANEL_ID}`)) panelChanged = true;\n          if (node.id === SHELL_HOST_ID || node.querySelector?.(`#${SHELL_HOST_ID}`)) panelChanged = true;\n        }\n      }\n      if (panelChanged || rootChanged) attachShellObserver();\n      if (panelChanged) schedulePanelMount();\n      if (rootChanged) attachConversationRoot();\n    });\n    documentObserver.observe(document.documentElement, { childList: true, subtree: true });\n    shellReadyListener = () => { attachShellObserver(); schedulePanelMount(); };\n    panelReadyListener = (event) => {\n      if (!event?.detail || String(event.detail) === 'local-agent') schedulePanelMount();\n    };\n    document.addEventListener('dcf:shell-ready', shellReadyListener, true);\n    document.addEventListener('dcf:panel-ready', panelReadyListener, true);\n    attachShellObserver();\n    schedulePanelMount();\n")
one("    conversationObserver?.disconnect(); documentObserver?.disconnect(); panelObserver?.disconnect();\n    clearInterval(mountTimer);", "    conversationObserver?.disconnect(); documentObserver?.disconnect(); panelObserver?.disconnect(); shellObserver?.disconnect();\n    if (shellReadyListener) document.removeEventListener('dcf:shell-ready', shellReadyListener, true);\n    if (panelReadyListener) document.removeEventListener('dcf:panel-ready', panelReadyListener, true);\n    clearInterval(mountTimer);")
one("      await waitForPanelMount(5000);\n      render();", "      if (!await waitForPanelMount(5000)) throw new Error('对话闭环未能挂载到本机 Agent 面板');\n      render();")
p.write_text(s)
