#!/bin/bash
#
# create-desktop-shortcut.sh — 在 ~/Desktop 生成真正的 DCF.app（裁定 C4）
#
# 生成目录式 macOS bundle：
#   ~/Desktop/DCF.app/Contents/Info.plist
#   ~/Desktop/DCF.app/Contents/MacOS/dcf-launcher   (可执行 shell)
#
# 双击 DCF.app：
#   1. 若 companion 未运行 -> nohup 后台拉起 seed/companion/index.js
#   2. nohup 后台拉起 Electron surface (packages/desktop-electron)
#   3. 全部日志重定向到 ~/.dcf/logs/，绝不弹 Terminal 窗口
#
# 幂等：重复运行只覆盖 bundle 内文件，不 rm 任何东西。
# 零 npm 依赖：纯 bash + 系统自带工具。

set -euo pipefail

# 仓库根：脚本所在目录的上一级
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

APP_DIR="$HOME/Desktop/DCF.app"
CONTENTS_DIR="$APP_DIR/Contents"
MACOS_DIR="$CONTENTS_DIR/MacOS"
LAUNCHER="$MACOS_DIR/dcf-launcher"

# node 的绝对路径在生成期解析（Finder 启动的进程 PATH 极小，
# 不含 nvm/homebrew 路径，必须写死）
NODE_BIN="$(command -v node || true)"
if [ -z "$NODE_BIN" ]; then
    echo "错误：找不到 node，可执行 launcher 需要它" >&2
    exit 1
fi

mkdir -p "$MACOS_DIR"

# ---------------------------------------------------------------------------
# Contents/Info.plist
# ---------------------------------------------------------------------------
cat > "$CONTENTS_DIR/Info.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>
    <string>DCF</string>
    <key>CFBundleDisplayName</key>
    <string>DCF</string>
    <key>CFBundleIdentifier</key>
    <string>dev.dcf.surface.launcher</string>
    <key>CFBundleVersion</key>
    <string>1.0</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleExecutable</key>
    <string>dcf-launcher</string>
    <key>LSUIElement</key>
    <true/>
</dict>
</plist>
PLIST

# ---------------------------------------------------------------------------
# Contents/MacOS/dcf-launcher — Finder 直接执行的入口，绝不弹 Terminal
# （REPO_ROOT / NODE_BIN 在生成期展开写死）
# ---------------------------------------------------------------------------
cat > "$LAUNCHER" <<LAUNCHER_EOF
#!/bin/bash
# DCF.app launcher — generated by scripts/create-desktop-shortcut.sh
# Finder 启动时无 Terminal、无继承 PATH，一切路径均为绝对路径。

REPO_ROOT="$REPO_ROOT"
NODE_BIN="$NODE_BIN"
LAUNCHER_EOF

cat >> "$LAUNCHER" <<'LAUNCHER_BODY'
LOG_DIR="$HOME/.dcf/logs"
mkdir -p "$LOG_DIR"

COMPANION_PORT_FILE="$HOME/.dcf/companion.port"
COMPANION_PORT=8472
if [ -f "$COMPANION_PORT_FILE" ]; then
    COMPANION_PORT="$(head -1 "$COMPANION_PORT_FILE" | tr -d '[:space:]')"
    [ -n "$COMPANION_PORT" ] || COMPANION_PORT=8472
fi

# 1. companion：健康则复用，不健康才后台拉起（companion 自带单实例语义）
if ! curl -sf --max-time 2 "http://127.0.0.1:${COMPANION_PORT}/rpc/health" >/dev/null 2>&1; then
    nohup "$NODE_BIN" "$REPO_ROOT/seed/companion/index.js" \
        >> "$LOG_DIR/companion.log" 2>&1 &
    # 给 doctor/监听一点启动时间
    sleep 1
fi

# 2. Electron surface
ELECTRON_BIN="$REPO_ROOT/packages/desktop-electron/node_modules/.bin/electron"
if [ -x "$ELECTRON_BIN" ]; then
    nohup "$ELECTRON_BIN" "$REPO_ROOT/packages/desktop-electron" \
        >> "$LOG_DIR/electron.log" 2>&1 &
else
    echo "$(date '+%F %T') electron binary missing: $ELECTRON_BIN" \
        >> "$LOG_DIR/electron.log"
fi

exit 0
LAUNCHER_BODY

chmod +x "$LAUNCHER"

# 让 Finder/LaunchServices 重新识别 bundle（缓存过的旧版本会被刷新）
touch "$APP_DIR"

echo "已生成 $APP_DIR"
echo "  REPO_ROOT = $REPO_ROOT"
echo "  NODE_BIN  = $NODE_BIN"
echo "双击 DCF.app 即可后台拉起 companion + Electron（日志在 ~/.dcf/logs/）"
