(function(){'use strict';
const UNIT_ID='dcf.firstparty.conversation-performance',UNIT_VERSION='1.0.0-rc.2',PANEL_ID='performance',HOST_ID='dcf-panel-performance',GLOBAL='__DCF_FIRSTPARTY_CONVERSATION_PERFORMANCE__';
const send=(m)=>chrome.runtime.sendMessage(m).then(r=>{if(!r||r.ok===false)throw new Error(r&&r.error||'DCF host rejected request');return r;});const prev=globalThis[GLOBAL];if(prev?.destroy)prev.destroy();
let panel,observer,timer,scrollHandler;const original=new Map();let settings={mode:'safe',threshold:24,window_size:40,batch_size:20},hiddenCount=0,lastDuration=0,applyCount=0,totalDuration=0,lastReason='startup';
function turns(){for(const s of ['[data-testid^="conversation-turn-"]','article[data-testid*="conversation-turn"]','main article']){const n=Array.from(document.querySelectorAll(s));if(n.length)return n;}return[];}function streaming(){return!!document.querySelector('[data-testid="stop-button"],button[aria-label*="Stop"],button[aria-label*="停止"]');}
function remember(n){if(!original.has(n))original.set(n,{contentVisibility:n.style.contentVisibility,containIntrinsicSize:n.style.containIntrinsicSize,display:n.style.display});}function restore(n){const p=original.get(n);if(!p)return;n.style.contentVisibility=p.contentVisibility;n.style.containIntrinsicSize=p.containIntrinsicSize;n.style.display=p.display;n.removeAttribute('data-dcf-performance');original.delete(n);}function restoreAll(){for(const n of Array.from(original.keys()))restore(n);hiddenCount=0;}
async function persist(){await send({type:'plugin.data.set',plugin_id:UNIT_ID,data:{settings}});}function report(){const list=turns();return{schema:'dcf.conversation-performance.runtime.v1',mode:settings.mode,turn_count:list.length,optimized_count:list.filter(n=>n.dataset.dcfPerformance).length,hidden_count:hiddenCount,content_visibility_supported:CSS?.supports?.('content-visibility','auto')||false,apply_count:applyCount,last_apply_duration_ms:Math.round(lastDuration*100)/100,total_apply_duration_ms:Math.round(totalDuration*100)/100,last_reason:lastReason};}
function apply(reason='mutation'){const start=performance.now();lastReason=reason;if(streaming())return;const list=turns();for(const n of Array.from(original.keys()))if(!n.isConnected)original.delete(n);hiddenCount=0;if(settings.mode==='off'||list.length<settings.threshold)restoreAll();else if(settings.mode==='safe'){for(const n of list){remember(n);n.style.display=original.get(n).display;n.style.contentVisibility='auto';n.style.containIntrinsicSize='auto 320px';n.dataset.dcfPerformance='safe';}}else{const cutoff=Math.max(0,list.length-settings.window_size);list.forEach((n,i)=>{remember(n);if(i<cutoff){n.style.display='none';n.style.contentVisibility=original.get(n).contentVisibility;n.style.containIntrinsicSize=original.get(n).containIntrinsicSize;n.dataset.dcfPerformance='hidden';hiddenCount++;}else{n.style.display=original.get(n).display;n.style.contentVisibility='auto';n.style.containIntrinsicSize='auto 320px';n.dataset.dcfPerformance='window';}});}lastDuration=performance.now()-start;applyCount++;totalDuration+=lastDuration;render();}
function schedule(reason){clearTimeout(timer);timer=setTimeout(()=>apply(reason),240);}function attach(){const root=document.querySelector('main')||document.querySelector('[role="main"]');if(!root){timer=setTimeout(attach,900);return;}observer?.disconnect();observer=new MutationObserver(()=>schedule('mutation'));observer.observe(root,{childList:true,subtree:true});apply('root-change');}
function style(){return`:host{display:block;font:13px/1.5 system-ui;color:inherit}.content{display:grid;gap:9px}.card{border:1px solid #ddd;border-radius:10px;padding:10px;background:#fff}.row{display:flex;gap:8px;align-items:center;flex-wrap:wrap}button,select{font:inherit;color:inherit;border:1px solid #bbb;background:#fff;border-radius:8px;padding:6px 9px}.primary{background:#202124;color:#fff;border-color:#202124}pre{white-space:pre-wrap;font:11px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace;background:#f4f4f4;padding:8px;border-radius:8px}@media(prefers-color-scheme:dark){.card{background:#222;border-color:#444}button,select{background:#292929;color:#f3f3f3;border-color:#555}.primary{background:#f3f3f3;color:#181818}pre{background:#171717}}`;}
function render(){if(!panel)return;const r=panel.shadowRoot;r.querySelector('.content').innerHTML=`<section class="card"><b>长对话减负</b><div class="row"><select data-role="mode"><option value="off">关闭</option><option value="safe">透明减负</option><option value="window">历史窗口</option></select><select data-role="window"><option value="20">保留最近 20 条</option><option value="40">保留最近 40 条</option><option value="80">保留最近 80 条</option></select></div><pre>${JSON.stringify(report(),null,2)}</pre><div class="row"><button data-action="expand">展开上一批</button><button data-action="restore">恢复全部并关闭</button></div></section>`;const mode=r.querySelector('[data-role="mode"]');mode.value=settings.mode;mode.onchange=async()=>{settings.mode=mode.value;if(settings.mode==='off')restoreAll();await persist();apply('mode-change');};const win=r.querySelector('[data-role="window"]');win.value=String(settings.window_size);win.onchange=async()=>{settings.window_size=Number(win.value);await persist();apply('window-size');};r.querySelector('[data-action="expand"]').onclick=async()=>{settings.window_size+=settings.batch_size;await persist();apply('manual-expand');};r.querySelector('[data-action="restore"]').onclick=async()=>{settings.mode='off';await persist();restoreAll();render();};}
function createPanel(){panel=document.createElement('section');panel.id=HOST_ID;panel.dataset.dcfPanelRoot='true';panel.dataset.dcfPanelId=PANEL_ID;panel.dataset.dcfPanelTitle='性能';panel.style.display='none';const r=panel.attachShadow({mode:'open'});r.innerHTML=`<style>${style()}</style><div class="content"></div>`;document.documentElement.append(panel);document.dispatchEvent(new CustomEvent('dcf:panel-ready',{detail:PANEL_ID}));}
function destroy(){clearTimeout(timer);observer?.disconnect();if(scrollHandler)window.removeEventListener('scroll',scrollHandler);restoreAll();panel?.remove();}globalThis[GLOBAL]={version:UNIT_VERSION,destroy,report:()=>report()};
try{document.getElementById(HOST_ID)?.remove();createPanel();send({type:'plugin.data.get',plugin_id:UNIT_ID}).then(async r=>{settings={...settings,...(r.data?.settings||{})};render();attach();scrollHandler=()=>{if(settings.mode==='window'&&window.scrollY<180&&!streaming()){settings.window_size+=settings.batch_size;persist().then(()=>apply('top-expand'));}};window.addEventListener('scroll',scrollHandler,{passive:true});await send({type:'unit.started',unit_id:UNIT_ID,version:UNIT_VERSION});}).catch(e=>send({type:'unit.failed',unit_id:UNIT_ID,version:UNIT_VERSION,error:String(e?.message||e)}));}catch(e){destroy();send({type:'unit.failed',unit_id:UNIT_ID,version:UNIT_VERSION,error:String(e?.message||e)}).catch(()=>{});}
})();
